"""Compatibility shim for paper option execution helpers."""
from __future__ import annotations

from src.trading.execution.paper_execution_options import (
    _broker_leg_refs_from_request,
    _build_execution_fallback_option_risk_input,
    _build_execution_fallback_option_trade_risk_request,
    _build_execution_fallback_trade_risk_request,
    _build_option_order_request,
    _close_option_order_request,
    _closing_position_intent,
    _fallback_option_strategy_payload,
    _generated_hedge_option_strategy_payload,
    _hedge_decision_action,
    _hedge_risk_decision_from_generated_action,
    _hedge_trading_decision_from_generated_action,
    _matching_open_option_position,
    _materialized_option_positions,
    _open_option_order_request,
    _opening_broker_leg_refs_from_request,
    _option_contract_symbol_from_payload,
    _option_decision_from_trading_decision,
    _paper_option_close_legs_from_position,
    _paper_option_legs_from_broker_refs,
    _paper_option_order_legs_from_decision,
    _remaining_fallback_expression_bucket_ids,
    _resolve_strategy_lifecycle_status,
    _risk_hedge_option_strategy_type,
)

__all__ = [
    "_broker_leg_refs_from_request",
    "_build_execution_fallback_option_risk_input",
    "_build_execution_fallback_option_trade_risk_request",
    "_build_execution_fallback_trade_risk_request",
    "_build_option_order_request",
    "_close_option_order_request",
    "_closing_position_intent",
    "_fallback_option_strategy_payload",
    "_generated_hedge_option_strategy_payload",
    "_hedge_decision_action",
    "_hedge_risk_decision_from_generated_action",
    "_hedge_trading_decision_from_generated_action",
    "_matching_open_option_position",
    "_materialized_option_positions",
    "_open_option_order_request",
    "_opening_broker_leg_refs_from_request",
    "_option_contract_symbol_from_payload",
    "_option_decision_from_trading_decision",
    "_paper_option_close_legs_from_position",
    "_paper_option_legs_from_broker_refs",
    "_paper_option_order_legs_from_decision",
    "_remaining_fallback_expression_bucket_ids",
    "_resolve_strategy_lifecycle_status",
    "_risk_hedge_option_strategy_type",
]
