services:
  scheduler:
    build: .
    container_name: scheduler
    command: ["sh", "-c", "python -u scripts/run_scheduler_service.py 2>&1 | tee -a /var/log/mono_db/stdout.log"]
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@postgres_db:5432/mono_db
      LOG_DIR: /var/log/mono_db
    volumes:
      - /data/mono_db_logs:/var/log/mono_db
    restart: unless-stopped
    networks:
      - postgres_network

networks:
  postgres_network:
    external: true
    name: postgres_network
