"""Strategy and candidate ORM models."""
from __future__ import annotations

import uuid

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Column,
    Date,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import relationship

from src.db.models.base import Base
from src.db.models.trading.enums import *

class StrategyDefinition(Base):
    """Versioned strategy metadata and JSON scoring/config policy."""

    __tablename__ = "strategy_definitions"

    strategy_definition_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    strategy_id = Column(String(64), nullable=False)
    version = Column(String(16), nullable=False)
    display_name = Column(String(128), nullable=False)
    strategy_layer = Column(String(32), nullable=False, index=True)
    typical_horizon = Column(String(32), nullable=False)
    allowed_common_stock_direction = Column(
        String(16),
        nullable=False,
        default="long_only",
        server_default="long_only",
    )
    config_json = Column(JSONB, nullable=False, default=dict)
    lifecycle_status = Column(
        String(16),
        nullable=False,
        default=StrategyLifecycleStatus.ACTIVE.value,
        server_default=StrategyLifecycleStatus.ACTIVE.value,
        index=True,
    )
    source = Column(
        String(32),
        nullable=False,
        default=StrategySource.SEED.value,
        server_default=StrategySource.SEED.value,
        index=True,
    )
    parent_strategy_id = Column(String(64), nullable=True)
    evidence_json = Column(JSONB, nullable=False, default=dict)
    is_active = Column(Boolean, nullable=False, default=True, server_default="true", index=True)
    created_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())

    __table_args__ = (
        UniqueConstraint("strategy_id", "version", name="uq_strategy_definitions_strategy_id_version"),
        CheckConstraint(
            "strategy_layer IN ('tactical_pattern', 'expression_bucket')",
            name="ck_strategy_definitions_strategy_layer",
        ),
        CheckConstraint(
            "allowed_common_stock_direction IN ('long_only')",
            name="ck_strategy_definitions_allowed_common_stock_direction",
        ),
        CheckConstraint(
            f"lifecycle_status IN {StrategyLifecycleStatus.check_in_sql()}",
            name="ck_strategy_definitions_lifecycle_status",
        ),
        CheckConstraint(
            f"source IN {StrategySource.check_in_sql()}",
            name="ck_strategy_definitions_source",
        ),
        Index("ix_strategy_definitions_strategy_id_version", "strategy_id", "version"),
    )

class StrategyProposal(Base):
    """Persisted strategy proposal generated by PR10."""

    __tablename__ = "strategy_proposals"

    strategy_proposal_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    trade_date = Column(Date, nullable=False, index=True)
    prompt_run_id = Column(
        UUID(as_uuid=True),
        ForeignKey("llm_prompt_runs.prompt_run_id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    daily_reflection_id = Column(
        UUID(as_uuid=True),
        ForeignKey("daily_reflections.daily_reflection_id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    proposal_status = Column(String(32), nullable=False, index=True)
    proposed_strategy_id = Column(String(64), nullable=False, index=True)
    display_name = Column(String(128), nullable=False)
    proposed_lifecycle_status = Column(String(16), nullable=True, index=True)
    duplicate_of_strategy_id = Column(String(64), nullable=True, index=True)
    rejection_reason = Column(String(128), nullable=True)
    source = Column(
        String(32),
        nullable=False,
        default=StrategySource.REFLECTION_LEARNING.value,
        server_default=StrategySource.REFLECTION_LEARNING.value,
        index=True,
    )
    evidence_summary = Column(Text, nullable=False)
    proposal_json = Column(JSONB, nullable=False, default=dict)
    metadata_json = Column(JSONB, nullable=False, default=dict)
    created_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())

    prompt_run = relationship("LlmPromptRun")
    daily_reflection = relationship("DailyReflection")
    evaluation_results = relationship("StrategyEvaluationResult", back_populates="strategy_proposal")

    __table_args__ = (
        CheckConstraint(
            f"proposal_status IN {StrategyProposalStatus.check_in_sql()}",
            name="ck_strategy_proposals_status",
        ),
        CheckConstraint(
            "proposed_lifecycle_status IS NULL OR "
            f"proposed_lifecycle_status IN {StrategyLifecycleStatus.check_in_sql()}",
            name="ck_strategy_proposals_lifecycle_status",
        ),
        CheckConstraint(
            f"source IN {StrategySource.check_in_sql()}",
            name="ck_strategy_proposals_source",
        ),
    )

class StrategyEvaluationResult(Base):
    """Persisted lifecycle evidence and promotion/retirement audit rows."""

    __tablename__ = "strategy_evaluation_results"

    strategy_evaluation_result_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    strategy_definition_id = Column(
        UUID(as_uuid=True),
        ForeignKey("strategy_definitions.strategy_definition_id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    strategy_proposal_id = Column(
        UUID(as_uuid=True),
        ForeignKey("strategy_proposals.strategy_proposal_id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    strategy_id = Column(String(64), nullable=False, index=True)
    evaluation_type = Column(String(64), nullable=False, index=True)
    evaluation_status = Column(String(16), nullable=False, index=True)
    prior_lifecycle_status = Column(String(16), nullable=True)
    new_lifecycle_status = Column(String(16), nullable=True, index=True)
    reason_code = Column(String(128), nullable=False)
    evidence_summary = Column(Text, nullable=False)
    metrics_json = Column(JSONB, nullable=False, default=dict)
    created_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())

    strategy_definition = relationship("StrategyDefinition")
    strategy_proposal = relationship("StrategyProposal", back_populates="evaluation_results")

    __table_args__ = (
        CheckConstraint(
            f"evaluation_status IN {StrategyEvaluationStatus.check_in_sql()}",
            name="ck_strategy_evaluation_results_status",
        ),
        CheckConstraint(
            "prior_lifecycle_status IS NULL OR "
            f"prior_lifecycle_status IN {StrategyLifecycleStatus.check_in_sql()}",
            name="ck_strategy_evaluation_results_prior_status",
        ),
        CheckConstraint(
            "new_lifecycle_status IS NULL OR "
            f"new_lifecycle_status IN {StrategyLifecycleStatus.check_in_sql()}",
            name="ck_strategy_evaluation_results_new_status",
        ),
    )

class StrategyRun(Base):
    """One candidate-scoring batch for a decision time."""

    __tablename__ = "strategy_runs"

    strategy_run_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    decision_time = Column(DateTime(timezone=True), nullable=False, index=True)
    snapshot_type = Column(String(32), nullable=False, index=True)
    status = Column(String(32), nullable=False, index=True)
    metadata_json = Column(JSONB, nullable=False, default=dict)
    created_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())

    candidate_scores = relationship("CandidateScore", back_populates="strategy_run")
    trade_classifications = relationship("TradeClassification", back_populates="strategy_run")
    watch_candidates = relationship("WatchCandidate", back_populates="strategy_run")

    __table_args__ = (
        CheckConstraint(
            "snapshot_type IN ('pre_open', 'intraday')",
            name="ck_strategy_runs_snapshot_type",
        ),
        CheckConstraint(
            f"status IN {StrategyRunStatus.check_in_sql()}",
            name="ck_strategy_runs_status",
        ),
    )

class CandidateScore(Base):
    """Ranked ticker candidate for one strategy definition."""

    __tablename__ = "candidate_scores"

    candidate_score_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    strategy_run_id = Column(
        UUID(as_uuid=True),
        ForeignKey("strategy_runs.strategy_run_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    signal_snapshot_id = Column(
        UUID(as_uuid=True),
        ForeignKey("signal_snapshots.signal_snapshot_id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    ticker = Column(String(16), nullable=False, index=True)
    strategy_id = Column(String(64), nullable=False, index=True)
    strategy_version = Column(String(16), nullable=False)
    strategy_definition_id = Column(
        UUID(as_uuid=True),
        ForeignKey("strategy_definitions.strategy_definition_id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    candidate_score = Column(Numeric, nullable=False)
    candidate_status = Column(String(32), nullable=False, index=True)
    direction = Column(String(32), nullable=False, index=True)
    action = Column(String(64), nullable=False)
    typical_horizon = Column(String(32), nullable=False)
    core_signal_evidence_json = Column(JSONB, nullable=False, default=dict)
    missing_required_signals_json = Column(JSONB, nullable=False, default=list)
    unsupported_missing_signal_families_json = Column(JSONB, nullable=False, default=list)
    invalidators_json = Column(JSONB, nullable=False, default=list)
    risk_tags_json = Column(JSONB, nullable=False, default=list)
    macro_compatibility = Column(String(32), nullable=False, index=True)
    selection_source = Column(String(32), nullable=False, index=True)
    manual_request_id = Column(UUID(as_uuid=True), nullable=True, index=True)
    selection_reason = Column(Text, nullable=False)
    rejection_reason = Column(String(128), nullable=True, index=True)
    benchmark_context_json = Column(JSONB, nullable=False, default=dict)
    decision_time = Column(DateTime(timezone=True), nullable=False, index=True)
    available_for_decision_at = Column(DateTime(timezone=True), nullable=False, index=True)
    source_record_refs_json = Column(JSONB, nullable=False, default=list)
    created_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())

    strategy_run = relationship("StrategyRun", back_populates="candidate_scores")
    signal_snapshot = relationship("SignalSnapshot")
    strategy_definition = relationship("StrategyDefinition")
    trade_classifications = relationship("TradeClassification", back_populates="candidate_score")
    watch_candidates = relationship("WatchCandidate", back_populates="candidate_score")
    outcome_evaluations = relationship("CandidateOutcomeEvaluation", back_populates="candidate_score")

    __table_args__ = (
        UniqueConstraint(
            "strategy_run_id",
            "ticker",
            "strategy_id",
            name="uq_candidate_scores_run_ticker_strategy",
        ),
        CheckConstraint(
            "candidate_score >= 0 AND candidate_score <= 1",
            name="ck_candidate_scores_score_range",
        ),
        CheckConstraint(
            f"candidate_status IN {CandidateStatus.check_in_sql()}",
            name="ck_candidate_scores_candidate_status",
        ),
        CheckConstraint(
            f"macro_compatibility IN {MacroCompatibility.check_in_sql()}",
            name="ck_candidate_scores_macro_compatibility",
        ),
        CheckConstraint(
            "selection_source IN ('scanner', 'manual_request', 'watchlist_pin', 'risk_manager')",
            name="ck_candidate_scores_selection_source",
        ),
        Index("ix_candidate_scores_run_score", "strategy_run_id", "candidate_score"),
        Index("ix_candidate_scores_ticker_strategy", "ticker", "strategy_id"),
    )

class WatchCandidate(Base):
    """Retained non-trade outcome linked to a scored strategy candidate."""

    __tablename__ = "watch_candidates"

    watch_candidate_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    candidate_score_id = Column(
        UUID(as_uuid=True),
        ForeignKey("candidate_scores.candidate_score_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    strategy_run_id = Column(
        UUID(as_uuid=True),
        ForeignKey("strategy_runs.strategy_run_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    ticker = Column(String(16), nullable=False, index=True)
    watch_strategy_id = Column(String(64), nullable=False, index=True)
    watch_strategy_version = Column(String(16), nullable=False)
    watch_type = Column(String(64), nullable=True, index=True)
    result_status = Column(String(64), nullable=False, index=True)
    watch_reason = Column(Text, nullable=False)
    selection_context_json = Column(JSONB, nullable=False, default=dict)
    decision_time = Column(DateTime(timezone=True), nullable=False, index=True)
    created_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())

    candidate_score = relationship("CandidateScore", back_populates="watch_candidates")
    strategy_run = relationship("StrategyRun", back_populates="watch_candidates")

    __table_args__ = (
        CheckConstraint(
            "watch_type IS NULL OR watch_type IN ('catalyst_watch', 'ordinary_watch')",
            name="ck_watch_candidates_watch_type",
        ),
        Index("ix_watch_candidates_ticker_strategy", "ticker", "watch_strategy_id"),
    )

class TradeClassification(Base):
    """Selected primary strategy context and portfolio-pool trade identity."""

    __tablename__ = "trade_classifications"

    trade_classification_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    candidate_score_id = Column(
        UUID(as_uuid=True),
        ForeignKey("candidate_scores.candidate_score_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    strategy_run_id = Column(
        UUID(as_uuid=True),
        ForeignKey("strategy_runs.strategy_run_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    ticker = Column(String(16), nullable=False, index=True)
    selected_strategy_id = Column(String(64), nullable=False, index=True)
    selected_strategy_version = Column(String(16), nullable=False)
    expression_bucket_id = Column(String(64), nullable=False, index=True)
    expression_bucket_version = Column(String(16), nullable=False)
    trade_identity = Column(String(64), nullable=False, index=True)
    watch_type = Column(String(64), nullable=True, index=True)
    direction = Column(String(32), nullable=False, index=True)
    intended_horizon = Column(String(32), nullable=False)
    exit_policy = Column(String(128), nullable=False)
    result_status = Column(String(64), nullable=False, index=True)
    classification_reason = Column(Text, nullable=False)
    selected_strategy_context_json = Column(JSONB, nullable=False, default=dict)
    decision_time = Column(DateTime(timezone=True), nullable=False, index=True)
    created_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())

    candidate_score = relationship("CandidateScore", back_populates="trade_classifications")
    strategy_run = relationship("StrategyRun", back_populates="trade_classifications")
    outcome_evaluations = relationship("CandidateOutcomeEvaluation", back_populates="trade_classification")

    __table_args__ = (
        CheckConstraint(
            f"trade_identity IN {TradeIdentity.check_in_sql()}",
            name="ck_trade_classifications_trade_identity",
        ),
        CheckConstraint(
            "watch_type IS NULL OR watch_type IN ('catalyst_watch', 'ordinary_watch')",
            name="ck_trade_classifications_watch_type",
        ),
        Index("ix_trade_classifications_ticker_strategy", "ticker", "selected_strategy_id"),
    )
